---
- name: Install "{{ pkg_name }}"  on clients
  hosts: webserver
  become: true
  vars:
    pkg_name: "docker"
  tasks:
  - name: Install Docker
    yum:
      name: "{{ pkg_name }}"
      state: latest
  - name: Restart Docker
    service:
      name: "{{ pkg_name }}"
      state: restarted
