pipeline {
    agent any
    tools {
    maven 'mvncfg'
    }

    stages {
      stage ('checkout code') {
         steps {
                git url: 'https://github.com/srinikolukula/prod.git'
             }
           }


        stage ('Compile Stage') {

            steps {
                    
                   sh 'mvn -f /web/pom.xml compile'
                
            }
        }

        stage ('Package Stage') {

            steps {
                    sh 'cd /web'
                    sh 'mvn package'
                
            }
        }


        
    }
}
