pipeline {
    agent any
    tools {
    maven 'mvncfg'
    }

    stages {
        stage ('Compile Stage') {

            steps {
                    
                    
                    sh 'mvn -f /var/lib/jenkins/workspace/pipeline/web/pom.xml mvn compile'
                
            }
        }

        stage ('Package Stage') {

            steps {
                    sh 'cd /opt/web'
                    sh 'mvn package'
                
            }
        }


        
    }
}
